Fix for #Pydev 1127: Integrate flake8 in Pydev
fabioz/Pydev pull request #325
Opened 2021-01-26 13:45 UTC by oluiscabral

2021-01-26 14:23 UTC, wesleybl commented
Flake8 has an option to ignore files:

https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations

It would be interesting for pydev to consider this setting and ignore the files. This would solve:

https://www.brainwy.com/tracker/PyDev/1124

2021-01-26 14:27 UTC, fabioz commented
> Flake8 has an option to ignore files:
> 
> https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations
> 
> It would be interesting for pydev to consider this setting and ignore the files. This would solve:
> 
> https://www.brainwy.com/tracker/PyDev/1124

Well, right now PyDev should run flake8 based on the project location, so, you should be able to configure the flake8 behaviour, but for ignoring code analysis in PyDev itself, we'd need a setting inside of PyDev, not really from an external tool.

2021-01-30 12:03 UTC, fabioz commented
Note: icon should be something as: https://www.stockio.com/free-icon/nature-icons-snowflake

2021-01-30 12:08 UTC, fabioz requested changes

2021-01-30 12:08 UTC, fabioz commented on plugins/org.python.pydev.shared_core/src/org/python/pydev/shared_core/IMiscConstants.java
> +    String FLAKE8_PROBLEM_MARKER = "org.python.pydev.flake8problemmaker";
Note: you also need to register the `flake8problemmaker` in the `org.python.pydev/plugin.xml` (search for `mypyproblemmarker`) in that file.

2021-02-20 15:29 UTC, fabioz commented
This was integrated in: https://github.com/fabioz/Pydev/commit/59140d0abb17230b3c7e1ac31da8463fba558607
Some additional fixes were done in: https://github.com/fabioz/Pydev/commit/6f7fd48309d3d3951d76f1ad2671c458fae28063

2021-02-20 15:29 UTC, closed without merging